kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
#$className = Enter Storage Class name :
  name: $className
provisioner: infinidat.com/fc
parameters:
#$poolName = Enter Pool name (default):
  pool_name: $poolName
#$ProvisionType = Enter provision type which should be used to provision volumes <thin/thick> (thin):
  provision_type: $ProvisionType
#$fstype = Enter filesystem type by which newly created volume should be formatted (ext4):
  fsType: $fstype
#$Bool_readonly = Do you want volumes to be readonly <true/false>(false):
  readonly: $Bool_readonly
#$Bool_SSDEnabled = Do you want SSD enabled for volumes (true):
  ssd_enabled: $Bool_SSDEnabled
#$reclaim = Enter reclaim policy for storage class <Delete/Retain> (Delete):
reclaimPolicy: $reclaim
