apiVersion: v1
kind: ServiceAccount
metadata:
  name: infinidat-provisioner
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: infinidat-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get"]
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["infinidat-provisioner"]
    verbs: ["use"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v100
metadata:
  name: run-infinidat-provisioner
subjects:
  - kind: ServiceAccount
    name: infinidat-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: infinidat-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: ConfigMap
apiVersion: v1
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: provisionerconfig
  namespace: default
data:
  pool_name: default
  provision_type: THIN
  nfs_mount_options: hard, rsize=1048576, wsize=1048576
  nfs_export_permissions: RW
  max_fs: "4000"
  max_volume: "100000"
  nfs_ssd_enabled: "false"
  nfs_no_root_squash: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: mgmt-api-credentials
type: Opaque
data:
  management_url: aHR0cDovLzE3Mi4yMC4yMTIuMTA0Lw==
  username: YWRtaW4=
  password: MTIzNDU2
---
kind: Deployment
apiVersion: extensions/v1
metadata:
  name: infinidat-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: infinidat-provisioner
    spec:
      serviceAccount: infinidat-provisioner
      containers:
        - name: infinidat-provisioner
          image: quay.io/nileshdsalunkhe/nfsprovi:latest
          args:
            - "-v=0"
          env:
            - name: MGMT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mgmt-api-credentials
                  key: username
            - name: MGMT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mgmt-api-credentials
                  key: password
            - name: MGMT_URL
              valueFrom:
                secretKeyRef:
                  name: mgmt-api-credentials
                  key: management_url
          imagePullPolicy: "Never"
          volumeMounts:
            - name: export-volume
              mountPath: /export 
      volumes:
        - name: export-volume
          hostPath:
            path: /tmp/infinidat-provisioner
---
